### PR TITLE
updated icons + thoughts

### PR DESCRIPTION
**Pull request by artemtrubnikov**
Added icons for tradeogre.com and premierleague.com but didn't change code.

Added thoughts folder to showcase optional icons.

Robinhood is the most inconsistent branding that I've seen so far. I can change it if you want. They have multiple currently running color schemes. Weird. (https://blog.logomyway.com/robinhood-logo/)
Video Lan looks outdated but that's how these guys roll (https://en.wikipedia.org/wiki/VLC_media_player)
YClients's radical redesign (https://www.yclients.com/en)

### CODE REVIEW

**Comment by tommycarpi** [comment]
> Added icons for tradeogre.com and premierleague.com but didn't change code.

Awesome, thanks! I'll update the index.json and close the issue opened for premier league

> Added thoughts folder to showcase optional icons.

I've checked it. I don't dislike the idea, but it will probably add unnecessary complexity to both the app and the maintenance of the icons.
What do you think?

> Robinhood is the most inconsistent branding that I've seen so far. I can change it if you want. They have multiple currently running color schemes. Weird. (https://blog.logomyway.com/robinhood-logo/)
> Video Lan looks outdated but that's how these guys roll (https://en.wikipedia.org/wiki/VLC_media_player)
> YClients's radical redesign (https://www.yclients.com/en)

- Robinhood: it's ok like this, don't worry!
- Yes, it's like Craigslist 😅


Before merging, could you add to gitignore the .DS_Store files to keep the repository cleaner?

**Comment by artemtrubnikov** [comment]
I've deleted my fork repository on my computer to clean clone it again.
Then I opened .gitignore in the root.
This is what I see from a clean download.
Is this sufficient or do I need to add other lines to this document?

I am new to GitHub. 😅

**Comment by tommycarpi** [comment]
No worries mate 😀

It should be good, just check that while creating the commit those files are not included and you are good to go 👍

**Comment by tommycarpi** [comment]
I can still see the .DS_Store from the first commit, the easiest way is to `copy/paste` the icons folder and create a new pull request without the .DS_Store

**Comment by artemtrubnikov** [comment]
> I can still see the .DS_Store from the first commit, the easiest way is to `copy/paste` the icons folder and create a new pull request without the .DS_Store

I've sent you an email on the topic to hello@getsentinel.io.

**Comment by tommycarpi** [comment]
Yup, just answered back 👍

**Comment by tommycarpi** [comment]
One more thing, there is a typo in the "premierleague" icon, it's missing the "u" ☺️

**Pull request merged**
